### ISSUE TITLE
[service_body_1] shortcode is showing IDs and parent.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bread#109] opened 2019-09-08 16:42 UTC
<img width="380" alt="image" src="https://user-images.githubusercontent.com/1850811/64491374-10986300-d236-11e9-9744-9a01d1406071.png">

configuration: 
[archsearch-canada09-08-2019.json.zip](https://github.com/bmlt-enabled/bread/files/3587796/archsearch-canada09-08-2019.json.zip)

**Comment by otrok7** [comment] 2019-09-08 23:51
I've been unable to reproduce this behavior.

**Comment by otrok7** [comment] 2019-09-09 09:44
@radius314 :  I can provoke this behavior if I use a custom query.  Is it possible that in the version that produced this error, you had a custom query?

**Comment by radius314** [comment] 2019-09-09 11:31
Yes it is using that feature.

**Comment by radius314** [comment] 2019-09-09 11:32
It’s also using custom query dynamic shortcodes.

**Comment by otrok7** [comment] 2019-09-09 11:47
Not sure what you mean by dynamic shortcodes...
    Am Montag, 9. September 2019, 13:32:04 MESZ hat Danny Gershman <notifications@github.com> Folgendes geschrieben:  
 
 It’s also using custom query dynamic shortcodes.

**Comment by radius314** [comment] 2019-09-09 23:31
There is a feature that allows you to set some shortcode values are dynamically set through a query string value.  This allows for trivial changes like titles or a minor query difference without having to have multiple templates.   The use case is a single template for all 50 states.

**Comment by radius314** [comment] 2019-09-09 23:31
https://github.com/bmlt-enabled/bread/blob/unstable/bmlt-meeting-list.php#L1487-L1491

**Comment by otrok7** [comment] 2019-09-10 08:48
Very cool.  Bread can still surprise me.  Do you think that this and the query string in the html query should be _REQUEST instead of _GET.  Also, maybe make this feature available in "custom_content" and "last_page" sections, too.  What do you think?

**Comment by radius314** [comment] 2019-09-10 12:21
There isn't much consumption of this feature, not sure it would be worth the maintenance of it.  Might be fine either way.

**Comment by otrok7** [comment] 2019-09-10 12:50
I don't think the average user is going to generate a query string and call Bread.  On the other hand, maybe this is a possibility for us as developers.  I had an early version of the meeting map that was for use by the regional PI committee.  The use case is, they wanted to inform therapies where nearby NA meetings are.  The user could select the location and zoom factor, and then with a push of a button, you could generate a query to send to Bread.  Bread would generate the meetings using a nice template, suitable for framing, or hanging up on the bulletin board....

**Comment by otrok7** [comment] 2019-09-14 22:53
fixed in 2.1.2

**Closed by otrok7** 2019-09-14 22:53 UTC
Labels: bug

**Comment by radius314** [comment] 2019-09-15 16:25
I have tested this and it looks good to me.  Thanks.
