### ISSUE TITLE
Font seems to be larger than normal on the default booklet setting.

### ISSUE THREAD

**Issue by radius314** [bmlt-enabled/bread#110] opened 2019-09-08 16:43 UTC
When using the default booklet setting, fonts appear to be much larger than they used to be.  To the extent that if one were using the feature out of the box, you'd immediately have to do some tweaking to get the text below the titles to fit on the first page (or break it to the second page).

**Comment by otrok7** [comment] 2019-09-09 00:05
This is a duplicate of #111.  2.1 creates the booklet a bit different from 1.10.  In 2.1, the pages are produced in the same size as they will eventually be printed.  The 5inch format in 1.10 generated the page first, as if the page own the whole sheet (rather than just half) then projected this into the booklet.

**Closed** 2019-09-10 12:21 UTC
Labels: duplicate

**Comment by radius314** [comment] 2019-09-15 16:26
I have tested this and it looks good. Thanks.
