### ISSUE TITLE
Issue uploading media

### ISSUE THREAD

**Issue by DeathCamel58** [bmlt-enabled/bread#220] opened 2024-12-26 14:10 UTC
`Media` -> `Add New Media File` brings me back to the `Media Library` when bread is enabled. This prevents us from uploading content to our site.

The webserver errors with one additional line to the `error_log` when this action is attempted.

```
[26-Dec-2024 13:57:58 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread1168131248 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[26-Dec-2024 13:58:24 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread769617164 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[26-Dec-2024 13:58:50 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread1808531846 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[26-Dec-2024 13:58:51 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread24997658 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[26-Dec-2024 13:58:51 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread251023411 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[26-Dec-2024 13:58:51 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread780486671 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[26-Dec-2024 13:58:54 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread329513076 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[26-Dec-2024 13:58:55 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread639332427 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[26-Dec-2024 13:58:55 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread655688262 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
```

Disabling this plugin, then going to `Media` -> `Add New Media File` works as intended.

Feel free to reach out for any additional information.

**Comment by otrok7** [comment] 2024-12-26 17:47
I think this problem is fixed by the beta here: https://github.com/bmlt-enabled/bread/releases/download/2.8.8-beta3/bread.zip.  I haven't been able to reproduce the problem locally and the other people that have reported this haven't gotten around to testing it.  So please test the beta and let me know if it helps.

**Comment by DeathCamel58** [comment] 2024-12-26 20:34
Just tested it. It works! :partying_face:

**Comment by otrok7** [comment] 2024-12-27 07:44
Fixed in 2.8.8

**Closed by otrok7** 2024-12-27 07:44 UTC

**Comment by DeathCamel58** [comment] 2025-01-06 12:57
The issue returned. Same issue, running `2.8.8`.

```
[05-Jan-2025 18:06:11 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread1198985699 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[05-Jan-2025 18:06:11 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread1258654965 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[05-Jan-2025 18:06:11 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread1478786873 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[05-Jan-2025 18:06:11 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread2011067783 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
[05-Jan-2025 18:06:11 UTC] PHP Warning:  filemtime(): stat failed for /tmp/bread495689218 in /home/grscna5/public_html/wp-content/plugins/bread/includes/class-bread.php on line 150
```

This time however, I can still upload new media, but I can't access the meeting list at `/?current-meeting-list=1`. Is there any additional information that you'd need to figure out what's going on?

**Comment by otrok7** [comment] 2025-01-06 13:22
Those messages in the log should not prevent you from generating a meeting list.  What happens when you access this meeting list/url?  Blank page?  Please post your JSON and also the complete URL.

**Comment by DeathCamel58** [comment] 2025-01-06 13:56
Complete URL: https://grscna.com/?current-meeting-list=1
JSON: [georgia-regional-service-committee-of-narcotics-anonymous-default-setting01-06-2025.json](https://github.com/user-attachments/files/18320237/georgia-regional-service-committee-of-narcotics-anonymous-default-setting01-06-2025.json)

I cleared my `error_log`, and visiting the page results in this:

```
[06-Jan-2025 13:55:03 UTC] PHP Fatal error:  Declaration of Psr\Log\NullLogger::log($level, Stringable|string $message, array $context = []): void must be compatible with Psr\Log\LoggerInterface::log($level, $message, array $context = []) in /home/grscna5/public_html/wp-content/plugins/bread/vendor/psr/log/src/NullLogger.php on line 22
```

**Comment by otrok7** [comment] 2025-01-06 14:15
Also, since bread seemed to be working before, what on your system has changed?  Any new plugins, updates, etc.?

**Comment by DeathCamel58** [comment] 2025-01-06 14:56
PHP version: `8.1.31`
WordPress Version: `6.7.1`

No clue what changed.

After disabling and re-enabling plugins, it turns out it was caused by the Cloudflare plugin. I appreciate your time!
